name: Deploy Website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: yarn install --frozen-lockfile
      
      - name: Install coscmd
        run: pip install coscmd

      - name: Generate COS config
        env:
          apiKeyId: ${{secrets.TCB_API_KEY_ID}}
          apiKey: ${{secrets.TCB_API_KEY}}
        run: coscmd config -a "$apiKeyId" -s "$apiKey" -b elvinn-wiki-1251269979 -r ap-guangzhou -m 16

      - name: Build project
        run: yarn build

      - name: Deploy to Tencent Cloud COS
        run: yarn deploy

  archive:
    if: failure()
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Archive Log
        uses: actions/upload-artifact@v3
        with:
          name: cloudbase-log
          path: ./*.log

