name: Deploy Website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: yarn install --frozen-lockfile

      - name: Login at Tencent Cloudbase
        env:
          apiKeyId: ${{secrets.TCB_API_KEY_ID}}
          apiKey: ${{secrets.TCB_API_KEY}}
        run: $(npm bin)/tcb login --apiKeyId "$apiKeyId" --apiKey "$apiKey"

      - name: Build project
        run: yarn build

      - name: Deploy to Tencent Cloudbase
        run: yarn deploy

  archive:
    if: failure()
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Archive Log
        uses: actions/upload-artifact@v2
        with:
          name: cloudbase-log
          path: ./*.log

